### PR TITLE
Upgrading to vue3

### PR DESCRIPTION
**Pull request by lovery**
Upgrading all dependencies to the latest version

### CODE REVIEW

**Comment by jackmcguire1** [comment]
@lovery maybe a good idea to update the README with example of mounting the component

**Comment by lovery** [comment]
> @lovery maybe a good idea to update the README with example of mounting the component

@jackmcguire1 I didn't change the way it is mounted, I kept everything the same.
May be only it is good to mention that after version 19 it required vue3, and not any more vue2.

By the way I am not sure but may be a better way is to create a new plugin with new name so it is really distinct that it needs vue3.

**Comment by rahulkumarsingh73690** [comment]
Looks good please merge

**Comment by rahulkumarsingh73690** [comment]
Please review this pr @SeregPie

**Comment by rahulkumarsingh73690** [comment]
Any update?

**Comment by SeregPie** [comment]
Thank you for the contribution. I will merge it into the dev:branch and check if it is really working.

**Pull request merged**
